name: ktye/k

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: checkout wg
      uses: actions/checkout@v2
      repository: https://github.com/ktye/wg
      path: wg
      
    - name: install ktye/wg
      with:
        go-version: 1.17
      working-directory: ./wg
      run: go install ./cmd/wg
      
    - name: checkout ktye/i
      uses: actions/setup-go@v2
      with:
        path: i

    - name: build ktye/i
      working-directory: ./i
      run: go build -v .

    - name: Test ktye/i
      working-directory: ./i
      run: go test -v .
