name: ktye/k

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: checkout ktye/i
      uses: actions/setup-go@v2
      with:
        path: i
   
    - name: checkout wg
      uses: actions/checkout@v2
      with:
        repository: https://github.com/ktye/wg
        path: wg
      
 
