name: ktye/k

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: checkout ktye/i
      uses: actions/checkout@v2
      with:
        path: i
   
    - name: checkout wg
      uses: actions/checkout@v2
      with:
        repository: ktye/wg
        path: wg
        
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    
    - name: install wg
      run: cd wg && go install ./cmd/wg

    - name: build i
      run: cd i && go build -v ./
      
    - name: test i
      run: cd i && go test

    - name: build k.c
      run: | 
        cd i
        wg -c -prefix ktye_ . > k.c
        gcc -o kc -O2 k.c -lm
    
    - name: test k.c
      run: cd i && ./kc k.t -e

    - name: upload k.c
      uses: actions/upload-artifact@v2
      with:
        name: k.c
        path: i/k.c
        
    - name: checkout sqlite
      uses: actions/checkout@v2
      with:
        repository: sqlite/sqlite
        path: sqlite
        ref: version-3.37.2

    - name: build sqlite.c
      run: |
        mkdir sq
        cd sq
        ../sqlite/configure
        make
        make sqlite3.c
        cp sqlite3.c ../i/+
          
    - name: build k+
      run: |
        sudo apt-get install -y liblapacke-dev libcairo2-dev libsqlite3-dev
        cd i/+
        sh mk.lin
        
    - name: test k+
      run: |
        ./k+ mat/mat.k -e
        ./k+ draw/draw.k -e
