name: ktye/k

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: set date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
   
    - name: checkout ktye/i
      uses: actions/checkout@v2
      with:
        path: i
   
    - name: checkout wg
      uses: actions/checkout@v2
      with:
        repository: ktye/wg
        path: wg
        
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    
    - name: install wg
      run: cd wg && go install ./cmd/wg
      
    - name: install wabt
      run: |
        wget https://github.com/WebAssembly/wabt/releases/download/1.0.26/wabt-1.0.26-ubuntu.tar.gz
        tar zxf wabt-1.0.26-ubuntu.tar.gz
        cp wabt-1.0.26/bin/wat2wasm .

    - name: build i
      run: cd i && go build -v ./
      
    - name: test i
      run: cd i && go test
    
    - name: build k.wasm
      run: |
        cd i
        wg             . > k.wat
        ../wat2wasm -o k.wasm k.wat

    - name: build k.c
      run: | 
        cd i
        wg -c -prefix ktye_ . > k.c
        gcc -o kc -O2 k.c -lm

    - name: test k.c
      run: cd i && ./kc k.t -e

    - name: k.f
      run: cd i/f77 && sh mk && sh mk test
    
    - name: k.go
      run: cd i/x && sh mk && sh mk gotest
      
    - name: kom
      run: cd i/kom && sh mk && sh mk test
  
#    - name: install k+ dependencies
#      run: sudo apt-get update && sudo apt-get install -y liblapacke-dev libcairo2-dev libsqlite3-dev libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
#  
#    - name: checkout sqlite
#      uses: actions/checkout@v2
#      with:
#        repository: sqlite/sqlite
#        path: sqlite
#        ref: version-3.37.2
#
#    - name: build sqlite.c
#      run: |
#        mkdir sq
#        cd sq
#        ../sqlite/configure
#        make
#        make sqlite3.c
#        cp sqlite3.c ../i/+
#        
#    - name: checkout raylib
#      uses: actions/checkout@v2
#      with:
#        repository: raysan5/raylib
#        ref: '4.0.0'
#        path: ray
#        
#    - name: build raylib
#      run: |
#        cd ray/src
#        make PLATFORM=PLATFORM_DESKTOP
#        cp ../libraylib.a ../../i/+/
#        cp raylib.h       ../../i/+/ray/
#        cp rgestures.h    ../../i/+/ray/
    
    - name: build ktye.h
      run: cd i/+ && sh mk ktye.h
    
#    - name: tar k+
#      run: cd i && tar czf k+.tar.gz +/
          
#    - name: build k+
#      run: |
#        cd i/+
#        sh mk.lin
#        
#    - name: test k+
#      run: |
#        cd i/+
#        ./k+ mat/mat.k -e
#        ./k+ draw/draw.k -e
        
    - name: delete release
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release ${{ steps.date.outputs.date }} ${{ github.ref }}
        
    - name: upload k.wasm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./i/k.wasm
        asset_name: k.wasm
        asset_content_type: application/wasm
        
    - name: upload k.go
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./x/k.go
        asset_name: k.go
        asset_content_type: text/plain
          
    - name: upload k.f
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./i/f77/k.f
        asset_name: k.f
        asset_content_type: text/plain

    - name: upload k.c
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./i/k.c
        asset_name: k.c
        asset_content_type: text/plain
    
    - name: upload ktye.h
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./i/+/ktye.h
        asset_name: ktye.h
        asset_content_type: text/plain
    
